GET http://localhost:3000/subscribers
###
GET http://localhost:3000/subscribers/6697d3d4bb88e35b38d077f7
###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "papanatas",
  "subscribedToChannel": "porno"
}

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "fulano",
  "subscribedToChannel": "no"
}

###
DELETE http://localhost:3000/subscribers/6697e3ffa57fbb638052f7f6

###
PATCH http://localhost:3000/subscribers/6697d3b2bb88e35b38d077f5
Content-Type: application/json

{
  "name": "nuevo nombre",
  "subscribedToChannel": "no"
}