GET http://localhost:3000/consultas
###
GET http://localhost:3000/consultas/2
###
POST http://localhost:3000/consultas
Content-Type: application/json

{
    "nombre_y_apellido": "Cocho Lopez",
    "tipo_consulta": "Nada",
    "URL_captura_problema": "URL3",
    "descripcion_problema": "###"
}
###

PUT http://localhost:3000/consultas/15
Content-Type: application/json

{
    "nombre_y_apellido": "Juan Perez",
    "tipo_consulta": "Técnica",
    "URL_captura_problema": "URL66",
    "descripcion_problema": "Esto es Postman"
}
###
DELETE http://localhost:3000/consultas/15